[package]
name = "token_with_refunds_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "bin"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
compressed_string = { path = "../../../aztec-nr/compressed-string" }
authwit = { path = "../../../aztec-nr/authwit" }
